### ISSUE TITLE
Redirect to create user form

### ISSUE THREAD

**Issue by dokuzbir** [danschultzer/coherence_assent#3]
I need to redirect to user create user form and from response auto fill some fileds, What is the best way redirect to user create user form, instead of create user?

**Comment by danschultzer** [comment]
Interesting use case. You do not need to record the binding then?

In that case, I would only use [the strategy modules in this library](https://github.com/danschultzer/coherence_assent/tree/1bed3bf45ae908f09249db8e4bfc2d336aa07a04/lib/coherence_assent/strategies), and have a controller that looks somewhat like this:

```elixir
defmodule MyApp.ProviderRegistrationController do
  @spec index(Conn.t, map) :: Conn.t
  def index(conn, _params) do
    config = Keyword.put(config(), :redirect_uri, callback_url(conn))
    {:ok, %{conn: conn, url: url}} = CoherenceAssent.Strategy.Github.authorize_url(conn, config)

    redirect(conn, external: url)
  end

  @spec callback(Conn.t, map) :: Conn.t
  def callback(conn, params) do
    params = Map.merge(%{"redirect_uri" => callback_url(conn)}, params)

    conn
    |> CoherenceAssent.Strategy.Github.callback(config(), params)
    |> redirect_create()
  end

  defp redirect_create({:ok, %{conn: conn, user: user}}) do
    conn
    |> put_session(:provider_info, user)
    |> redirect(to: user_path(conn, :new))
  end
  defp redirect_create({:error, %{error: error}}) do
    raise error
  end

  defp config do
    config = Application.get_env(:my_app, :github_details)
  end

  defp callback_url(conn) do
    provider_registration_url(conn, :callback)
  end
end
```

Then in the user registration controller, you can just load in details from the session. This could obviously also be done entirely without the redirect/session, and you could just show the create form in this controller.

**Comment by dokuzbir** [comment]
Thanks really helpfull. I will to create user identify too. So i want to be able to create without password.

**Comment by danschultzer** [comment]
I see. Then it might be better for you to check out how required login field is handled (it might even be what you're looking for). When you set the Coherence config with `login_field`, CoherenceAssent will look up to make sure that the field is set. In most cases, it's the email. If the login field not available from the provider, the user will be required to fill out the field before registering.

I don't know your exact use case, so I'll just show some of the code that handles this:

https://github.com/danschultzer/coherence_assent/blob/22dfb5a60bc25a5418eb4fdb7f83f35628abb752/lib/coherence_assent/callback.ex#L36-L57

https://github.com/danschultzer/coherence_assent/blob/1bed3bf45ae908f09249db8e4bfc2d336aa07a04/lib/coherence_assent/web/controllers/controller.ex#L24-L28

**Comment by dokuzbir** [comment]
My problem is password. If i use new changeset without validate password, can that cause some security problems? or is there a function in coherence assent for that ?

**Comment by danschultzer** [comment]
In this case I would say no, that isn’t a security issue. The user still needs to authenticate themselves by using a provider. For security it might even be preferable to use a provider rather than a possible insecure/leaked password that the user could enter. If you want to add some extra security for when users update their information, you could require them to reauthenticate themselves before they can view that page. In any case, the authentication is kept in controller/plug layer.

**Comment by dokuzbir** [comment]
But can a user login account without input password with that way?

**Comment by danschultzer** [comment]
Yeah, they can log in with the provider, they don’t need to enter a password.

**Comment by dokuzbir** [comment]
i mean with that way user wont have a password so can a user login without proviider and password. If they request with email field and empty password. Isnt that a security issue ? sorry i am not experienced programmer. I want to be sure

**Comment by danschultzer** [comment]
It won't be an issue because they still have to authenticate with the provider. You can require that the user fills out a new password when they update their information the first time, but that might defeat the purpose of making your app easy, and secure.

We've to care about both user experience and security, and we would like to have passwords that are as random as possible. So forcing users to write in a password, when they could just use their provider might actually decrease the security of your website as they might feel like just writing in a common insecure password.

The reason that websites usually asks users to enter their passwords before they can update their information is because of long-term sessions (the `remember me` checkbox). We want to make sure the session is used by the actual owner and not someone else (e.g. on a shared computer, or more rare, session highjacking). The solution to make this as secure as possible is very simple: Always require users to reauthenticate with their provider whenever the session expires.

You bring up a good point, and I think this is something CoherenceAssent should explicitly require for the sessions created through provider authentication.
